#!/usr/bin/env python3
"""
Open the next batch of Overseerr request pages from a prepared review JSON file.

This helper does not submit requests. It opens the best-match pages so the user
can quickly click Request manually and move on.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import time
import webbrowser
from typing import Any


CONFIDENCE_ORDER = {"none": 0, "low": 1, "medium": 2, "high": 3}
DEFAULT_REVIEW_CANDIDATES = [
    pathlib.Path.home() / "Desktop" / "Overseerr_ReRequest_Final_Cleaned_overseerr_review.json",
    pathlib.Path.home() / "Desktop" / "Overseerr_ReRequest_Mega_List_overseerr_review.json",
]


def default_review_json() -> pathlib.Path:
    for candidate in DEFAULT_REVIEW_CANDIDATES:
        if candidate.exists():
            return candidate
    return DEFAULT_REVIEW_CANDIDATES[0]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Open the next batch of prepared Overseerr request pages."
    )
    parser.add_argument(
        "review_json",
        nargs="?",
        default=str(default_review_json()),
        help=(
            "Path to the review JSON generated by prepare_overseerr_request_review.py. "
            f"Default: {default_review_json()}"
        ),
    )
    parser.add_argument(
        "--count",
        type=int,
        default=12,
        help="How many pages to open in this batch. Default: 12",
    )
    parser.add_argument(
        "--min-confidence",
        choices=["low", "medium", "high"],
        default="medium",
        help="Lowest confidence level to open automatically. Default: medium",
    )
    parser.add_argument(
        "--state-file",
        default="",
        help="Path to the opener state file. Defaults next to the review JSON.",
    )
    parser.add_argument(
        "--include-available",
        action="store_true",
        help="Include entries already marked available in Overseerr.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the next batch instead of opening browser tabs.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Clear saved opener progress before selecting the next batch.",
    )
    parser.add_argument(
        "--pause-ms",
        type=int,
        default=150,
        help="Pause between opening tabs in milliseconds. Default: 150",
    )
    return parser.parse_args()


def load_review(path: pathlib.Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise RuntimeError(f"Expected a list in review JSON: {path}")
    return payload


def default_state_path(review_path: pathlib.Path) -> pathlib.Path:
    return review_path.with_name(review_path.stem + "_open_state.json")


def load_state(path: pathlib.Path, reset: bool) -> dict[str, Any]:
    if reset or not path.exists():
        return {"seen_ids": [], "history": [], "cycle_number": 1}
    state = json.loads(path.read_text(encoding="utf-8"))
    if "seen_ids" not in state:
        history = state.get("history", [])
        type_by_title: dict[str, str] = {}
        for item in history:
            title = normalize_title(str(item.get("input_title") or ""))
            url = str(item.get("best_match_url") or "")
            media_type = ""
            if "/movie/" in url:
                media_type = "movie"
            elif "/tv/" in url:
                media_type = "tv"
            if title:
                type_by_title[title] = media_type

        legacy_keys = state.get("opened_keys", [])
        converted: list[str] = []
        for raw in legacy_keys:
            title = normalize_title(str(raw).split("::", 1)[-1])
            media_type = type_by_title.get(title, "")
            converted.append(f"{media_type}::{title}")
        state["seen_ids"] = converted
    else:
        normalized_seen: list[str] = []
        for raw in state.get("seen_ids", []):
            raw_str = str(raw)
            if "::" in raw_str:
                media_type, title = raw_str.split("::", 1)
                normalized_seen.append(f"{media_type}::{normalize_title(title)}")
            else:
                normalized_seen.append(f"::{normalize_title(raw_str)}")
        state["seen_ids"] = normalized_seen
    state.setdefault("history", [])
    state.setdefault("cycle_number", 1)
    return state


def save_state(path: pathlib.Path, state: dict[str, Any]) -> None:
    path.write_text(json.dumps(state, indent=2), encoding="utf-8")


def normalize_title(value: str) -> str:
    value = (value or "").casefold().strip()
    value = re.sub(r'^\s*"|"\s*$', "", value)
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def row_identity(row: dict[str, Any]) -> str:
    best_match_id = row.get("best_match_id")
    best_match_type = str(row.get("best_match_type") or "")
    if best_match_type and best_match_id not in (None, ""):
        return f"{best_match_type}::{best_match_id}"
    title = normalize_title(str(row.get("input_title") or ""))
    return f"{best_match_type}::{title}"


def is_eligible(row: dict[str, Any], min_confidence: str, include_available: bool) -> bool:
    if not row.get("best_match_url"):
        return False
    if CONFIDENCE_ORDER.get(str(row.get("best_match_confidence", "none")), 0) < CONFIDENCE_ORDER[min_confidence]:
        return False
    if not include_available and bool(row.get("best_match_available")):
        return False
    return True


def main() -> int:
    args = parse_args()
    review_path = pathlib.Path(args.review_json)
    if not review_path.exists():
        raise SystemExit(f"Review JSON not found: {review_path}")

    state_path = pathlib.Path(args.state_file) if args.state_file else default_state_path(review_path)
    review = load_review(review_path)
    state = load_state(state_path, args.reset)

    seen_ids = set(state.get("seen_ids", []))
    eligible = [row for row in review if is_eligible(row, args.min_confidence, args.include_available)]
    eligible_ids = {row_identity(row) for row in eligible}

    # Drop stale progress markers for titles that are no longer eligible/current.
    seen_ids &= eligible_ids
    unseen = [row for row in eligible if row_identity(row) not in seen_ids]

    # Once every eligible title has been shown once, start a new cycle automatically.
    if not unseen and eligible:
        seen_ids = set()
        unseen = eligible
        state["cycle_number"] = int(state.get("cycle_number", 1)) + 1

    batch = unseen[: args.count]

    summary = {
        "review_json": str(review_path),
        "state_file": str(state_path),
        "requested_batch_count": args.count,
        "selected_count": len(batch),
        "eligible_count": len(eligible),
        "remaining_in_cycle_after_this_batch": max(len(unseen) - len(batch), 0),
        "cycle_number": state.get("cycle_number", 1),
        "min_confidence": args.min_confidence,
        "include_available": args.include_available,
        "dry_run": args.dry_run,
        "titles": [
            {
                "line_number": row.get("line_number"),
                "input_title": row.get("input_title"),
                "best_match_title": row.get("best_match_title"),
                "best_match_type": row.get("best_match_type"),
                "best_match_confidence": row.get("best_match_confidence"),
                "best_match_url": row.get("best_match_url"),
            }
            for row in batch
        ],
    }

    if args.dry_run:
        print(json.dumps(summary, indent=2))
        return 0

    for row in batch:
        webbrowser.open_new_tab(str(row["best_match_url"]))
        row_id = row_identity(row)
        seen_ids.add(row_id)
        state.setdefault("history", []).append(
            {
                "line_number": row.get("line_number"),
                "input_title": row.get("input_title"),
                "best_match_title": row.get("best_match_title"),
                "identity": row_id,
                "cycle_number": state.get("cycle_number", 1),
                "best_match_url": row.get("best_match_url"),
                "opened_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            }
        )
        time.sleep(max(args.pause_ms, 0) / 1000.0)

    state["seen_ids"] = sorted(seen_ids)
    save_state(state_path, state)
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
