---
title: Harbor Media Server
theme: dark
color: slate
headerStyle: clean
layout:
  Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 3
  Photos & Management:
    style: row
    columns: 4
  Optimization:
    style: row
    columns: 1
